const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Physics: 0},
	{Rotate: 0},
	{Red: 0},
	{Day: 0},
	{Solid: 0},
	{Base: 0},
	{Touch: 0},
	{UnderPipe: 0},
	{UpperPipe: 0},
	{Keyboard: 0},
	{SpriteFont: 0},
	{Score: 0},
	{Audio: 0},
	{BackOver: 0},
	{GameOver: 0},
	{Sine: 0},
	{Menu: 0},
	{Menu2: 0},
	{Pause: 0},
	{Home: 0},
	{Tween: 0},
	{Transition: 0},
	{Speed: 0},
	{SpawnTime: 0},
	{Active: 0},
	{Start: 0},
	{Random_: 0},
	{Enter: 0}
];

self.InstanceType = {
	Red: class extends self.ISpriteInstance {},
	Day: class extends self.ITiledBackgroundInstance {},
	Base: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	UnderPipe: class extends self.ISpriteInstance {},
	UpperPipe: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Score: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BackOver: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Menu2: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {}
}